/*
 * SPDX-License-Identifier: MIT
 * 
 * Italian Web UI for color detection configuration
 */

#ifndef WEB_UI_H
#define WEB_UI_H

static const char web_ui_html[] = "<!DOCTYPE html>\n"
"<html lang=\"it\">\n"
"<head>\n"
"    <meta charset=\"UTF-8\">\n"
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
"    <title>ESP32-S3 Camera - Rilevamento Colori</title>\n"
"    <style>\n"
"        body { font-family: Arial, sans-serif; margin: 20px; background: #f0f0f0; }\n"
"        .container { max-width: 1200px; margin: 0 auto; background: white; padding: 20px; border-radius: 8px; }\n"
"        h1 { color: #333; border-bottom: 2px solid #4CAF50; padding-bottom: 10px; }\n"
"        h2 { color: #666; margin-top: 20px; }\n"
"        .stream-container { text-align: center; margin: 20px 0; }\n"
"        .stream-container img { max-width: 100%; border: 2px solid #ddd; border-radius: 4px; }\n"
"        .config-section { background: #f9f9f9; padding: 15px; margin: 15px 0; border-radius: 4px; }\n"
"        .color-group { margin: 10px 0; padding: 10px; border-left: 4px solid #ccc; }\n"
"        .color-group.red { border-left-color: #f44336; }\n"
"        .color-group.green { border-left-color: #4CAF50; }\n"
"        .color-group.blue { border-left-color: #2196F3; }\n"
"        label { display: inline-block; width: 120px; margin: 5px 0; }\n"
"        input[type=\"number\"] { width: 80px; padding: 5px; border: 1px solid #ddd; border-radius: 3px; }\n"
"        button { background: #4CAF50; color: white; padding: 10px 20px; border: none; border-radius: 4px; cursor: pointer; margin: 5px; }\n"
"        button:hover { background: #45a049; }\n"
"        .button-secondary { background: #2196F3; }\n"
"        .button-secondary:hover { background: #0b7dda; }\n"
"        .status { padding: 10px; margin: 10px 0; border-radius: 4px; }\n"
"        .status.success { background: #d4edda; color: #155724; }\n"
"        .status.error { background: #f8d7da; color: #721c24; }\n"
"    </style>\n"
"</head>\n"
"<body>\n"
"    <div class=\"container\">\n"
"        <h1>ESP32-S3 Camera - Rilevamento Bande RGB</h1>\n"
"        \n"
"        <div class=\"stream-container\">\n"
"            <h2>Stream Video MJPEG</h2>\n"
"            <img id=\"stream\" src=\"/stream\" alt=\"Camera Stream\">\n"
"        </div>\n"
"        \n"
"        <div class=\"config-section\">\n"
"            <h2>Configurazione Rilevamento Colori</h2>\n"
"            <div id=\"status\"></div>\n"
"            \n"
"            <div class=\"color-group red\">\n"
"                <h3>Soglie Rosso (HSV)</h3>\n"
"                <label>H Min:</label><input type=\"number\" id=\"red_h_min\" min=\"0\" max=\"255\" value=\"0\"><br>\n"
"                <label>H Max:</label><input type=\"number\" id=\"red_h_max\" min=\"0\" max=\"255\" value=\"10\"><br>\n"
"                <label>S Min:</label><input type=\"number\" id=\"red_s_min\" min=\"0\" max=\"255\" value=\"100\"><br>\n"
"                <label>S Max:</label><input type=\"number\" id=\"red_s_max\" min=\"0\" max=\"255\" value=\"255\"><br>\n"
"                <label>V Min:</label><input type=\"number\" id=\"red_v_min\" min=\"0\" max=\"255\" value=\"100\"><br>\n"
"                <label>V Max:</label><input type=\"number\" id=\"red_v_max\" min=\"0\" max=\"255\" value=\"255\"><br>\n"
"            </div>\n"
"            \n"
"            <div class=\"color-group green\">\n"
"                <h3>Soglie Verde (HSV)</h3>\n"
"                <label>H Min:</label><input type=\"number\" id=\"green_h_min\" min=\"0\" max=\"255\" value=\"40\"><br>\n"
"                <label>H Max:</label><input type=\"number\" id=\"green_h_max\" min=\"0\" max=\"255\" value=\"80\"><br>\n"
"                <label>S Min:</label><input type=\"number\" id=\"green_s_min\" min=\"0\" max=\"255\" value=\"100\"><br>\n"
"                <label>S Max:</label><input type=\"number\" id=\"green_s_max\" min=\"0\" max=\"255\" value=\"255\"><br>\n"
"                <label>V Min:</label><input type=\"number\" id=\"green_v_min\" min=\"0\" max=\"255\" value=\"100\"><br>\n"
"                <label>V Max:</label><input type=\"number\" id=\"green_v_max\" min=\"0\" max=\"255\" value=\"255\"><br>\n"
"            </div>\n"
"            \n"
"            <div class=\"color-group blue\">\n"
"                <h3>Soglie Blu (HSV)</h3>\n"
"                <label>H Min:</label><input type=\"number\" id=\"blue_h_min\" min=\"0\" max=\"255\" value=\"100\"><br>\n"
"                <label>H Max:</label><input type=\"number\" id=\"blue_h_max\" min=\"0\" max=\"255\" value=\"140\"><br>\n"
"                <label>S Min:</label><input type=\"number\" id=\"blue_s_min\" min=\"0\" max=\"255\" value=\"100\"><br>\n"
"                <label>S Max:</label><input type=\"number\" id=\"blue_s_max\" min=\"0\" max=\"255\" value=\"255\"><br>\n"
"                <label>V Min:</label><input type=\"number\" id=\"blue_v_min\" min=\"0\" max=\"255\" value=\"100\"><br>\n"
"                <label>V Max:</label><input type=\"number\" id=\"blue_v_max\" min=\"0\" max=\"255\" value=\"255\"><br>\n"
"            </div>\n"
"            \n"
"            <div class=\"color-group\">\n"
"                <h3>Parametri Generali</h3>\n"
"                <label>Area Minima (px):</label><input type=\"number\" id=\"min_area\" min=\"100\" max=\"5000\" value=\"900\"><br>\n"
"                <label>Confidenza Min (%):</label><input type=\"number\" id=\"min_confidence\" min=\"0\" max=\"100\" value=\"60\"><br>\n"
"                <label>Decimazione Frame:</label><input type=\"number\" id=\"frame_decimation\" min=\"1\" max=\"60\" value=\"15\"><br>\n"
"            </div>\n"
"            \n"
"            <button onclick=\"loadConfig()\">Carica Configurazione</button>\n"
"            <button onclick=\"saveConfig()\" class=\"button-secondary\">Salva Configurazione</button>\n"
"        </div>\n"
"    </div>\n"
"    \n"
"    <script>\n"
"        function showStatus(message, isError) {\n"
"            const statusDiv = document.getElementById('status');\n"
"            statusDiv.className = 'status ' + (isError ? 'error' : 'success');\n"
"            statusDiv.textContent = message;\n"
"            setTimeout(() => statusDiv.textContent = '', 3000);\n"
"        }\n"
"        \n"
"        function loadConfig() {\n"
"            fetch('/api/config')\n"
"                .then(response => response.json())\n"
"                .then(data => {\n"
"                    document.getElementById('red_h_min').value = data.red.h_min;\n"
"                    document.getElementById('red_h_max').value = data.red.h_max;\n"
"                    document.getElementById('red_s_min').value = data.red.s_min;\n"
"                    document.getElementById('red_s_max').value = data.red.s_max;\n"
"                    document.getElementById('red_v_min').value = data.red.v_min;\n"
"                    document.getElementById('red_v_max').value = data.red.v_max;\n"
"                    \n"
"                    document.getElementById('green_h_min').value = data.green.h_min;\n"
"                    document.getElementById('green_h_max').value = data.green.h_max;\n"
"                    document.getElementById('green_s_min').value = data.green.s_min;\n"
"                    document.getElementById('green_s_max').value = data.green.s_max;\n"
"                    document.getElementById('green_v_min').value = data.green.v_min;\n"
"                    document.getElementById('green_v_max').value = data.green.v_max;\n"
"                    \n"
"                    document.getElementById('blue_h_min').value = data.blue.h_min;\n"
"                    document.getElementById('blue_h_max').value = data.blue.h_max;\n"
"                    document.getElementById('blue_s_min').value = data.blue.s_min;\n"
"                    document.getElementById('blue_s_max').value = data.blue.s_max;\n"
"                    document.getElementById('blue_v_min').value = data.blue.v_min;\n"
"                    document.getElementById('blue_v_max').value = data.blue.v_max;\n"
"                    \n"
"                    document.getElementById('min_area').value = data.min_area;\n"
"                    document.getElementById('min_confidence').value = data.min_confidence;\n"
"                    document.getElementById('frame_decimation').value = data.frame_decimation;\n"
"                    \n"
"                    showStatus('Configurazione caricata con successo!', false);\n"
"                })\n"
"                .catch(err => showStatus('Errore nel caricamento: ' + err, true));\n"
"        }\n"
"        \n"
"        function saveConfig() {\n"
"            const config = {\n"
"                red: {\n"
"                    h_min: parseInt(document.getElementById('red_h_min').value),\n"
"                    h_max: parseInt(document.getElementById('red_h_max').value),\n"
"                    s_min: parseInt(document.getElementById('red_s_min').value),\n"
"                    s_max: parseInt(document.getElementById('red_s_max').value),\n"
"                    v_min: parseInt(document.getElementById('red_v_min').value),\n"
"                    v_max: parseInt(document.getElementById('red_v_max').value)\n"
"                },\n"
"                green: {\n"
"                    h_min: parseInt(document.getElementById('green_h_min').value),\n"
"                    h_max: parseInt(document.getElementById('green_h_max').value),\n"
"                    s_min: parseInt(document.getElementById('green_s_min').value),\n"
"                    s_max: parseInt(document.getElementById('green_s_max').value),\n"
"                    v_min: parseInt(document.getElementById('green_v_min').value),\n"
"                    v_max: parseInt(document.getElementById('green_v_max').value)\n"
"                },\n"
"                blue: {\n"
"                    h_min: parseInt(document.getElementById('blue_h_min').value),\n"
"                    h_max: parseInt(document.getElementById('blue_h_max').value),\n"
"                    s_min: parseInt(document.getElementById('blue_s_min').value),\n"
"                    s_max: parseInt(document.getElementById('blue_s_max').value),\n"
"                    v_min: parseInt(document.getElementById('blue_v_min').value),\n"
"                    v_max: parseInt(document.getElementById('blue_v_max').value)\n"
"                },\n"
"                min_area: parseInt(document.getElementById('min_area').value),\n"
"                min_confidence: parseInt(document.getElementById('min_confidence').value),\n"
"                frame_decimation: parseInt(document.getElementById('frame_decimation').value)\n"
"            };\n"
"            \n"
"            fetch('/api/config', {\n"
"                method: 'POST',\n"
"                headers: { 'Content-Type': 'application/json' },\n"
"                body: JSON.stringify(config)\n"
"            })\n"
"            .then(response => response.json())\n"
"            .then(data => showStatus('Configurazione salvata con successo!', false))\n"
"            .catch(err => showStatus('Errore nel salvataggio: ' + err, true));\n"
"        }\n"
"        \n"
"        // Load config on page load\n"
"        window.onload = loadConfig;\n"
"    </script>\n"
"</body>\n"
"</html>";

#endif // WEB_UI_H
